[package]
name = "atom"
version = "0.1.0"
authors = ["Izzy Swart"]
edition = "2018"

[dependencies]
lmdb = "0.8.0"
serde_json = "1.0.39"
failure = "0.1.5"

[dependencies.serde]
version = "1.0.92"
features = ["derive"]
